version: '3.8'

services:
  uptime-buddy-api:
    network_mode: "host"
    image: schech1/uptime-buddy-api:latest
    ports:
      - "5005:5005" # If you change the port, also change the PORT Env var
    environment:
      - UPTIME_KUMA_URL=YOUR_UPTIME_KUMA_URL # e.g. http://192.168.1.34:3002/
      - EXTERNAL_URL=YOUR_EXTERNAL_URL_FOR_THE_BACKEND # e.g. https://uptime.domain.com
      - USERNAME=YOUR_UPTIME_KUMA_USERNAME #Optional: remove line if auth is disabled in Uptime Kuma
      - PASSWORD=YOUR_UPTIME_KUMA_PASSWORD #Optional: remove line if auth is disabled in Uptime Kuma
      - TOKEN=SECRET_TOKEN # Created by iOS-App
      - PORT=NEW_PORT # If you change the port above, adjust this var accordingly. E.g. 5003
